steps:
- name: 'python:3.12-slim'
  entrypoint: 'bash'
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-east1-docker.pkg.dev/fabled-cooler-399708/installtheprint/installtheprint01', '.' ]
images: ['asia-east1-docker.pkg.dev/fabled-cooler-399708/installtheprint/installtheprint01']